version: '3'
services:
  nginx:
    image: 'nginx:stable'
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
  mysql:
    image: mysql:8.0.29-oracle
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: cutaoto
      MYSQL_PASSWORD: cutaoto
      MYSQL_ROOT_PASSWORD: cutaoto
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOSTS=mysql
      - PMA_PORT=3306
      - PMA_USER=cutaoto
      - PMA_PASSWORD=cutaoto
